<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Serve per ILogger, IConfiguration e IOptions senza usare l'SDK Web. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowDesk.Domain\FlowDesk.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" />
  </ItemGroup>

</Project>
